'\" t
.\"     Title: vmpk
.\"    Author: Mehdi Dogguy <dogguy@pps.jussieu.fr>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: Dec 24, 2024
.\"    Manual: User Commands
.\"    Source: vmpk 0.9.1
.\"  Language: English
.\"
.TH "VMPK" "1" "Dec 24, 2024" "vmpk 0\&.9\&.1" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
vmpk \- Virtual MIDI Piano Keyboard
.SH "SYNOPSIS"
.HP \w'\fBvmpk\fR\ 'u
\fBvmpk\fR [options\&.\&.\&.]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBvmpk\fR
program\&.
.PP
This program uses standard Qt options\&.
.PP
Virtual MIDI Piano Keyboard is a MIDI events generator and receiver\&. It doesn\*(Aqt produce any sound by itself, but can be used to drive a MIDI synthesizer (either hardware or software, internal or external)\&. You can use the computer\*(Aqs keyboard to play MIDI notes, and also the mouse\&. You can use the Virtual MIDI Piano Keyboard to display the played MIDI notes from another instrument or MIDI file player\&.
.SH "VMPK OPTIONS"
.PP
The following options apply to
\fBvmpk\fR
only:
.PP
\fB\-h|\-\-help\fR
.RS 4
Displays a help text\&.
.RE
.PP
\fB\-v|\-\-version\fR
.RS 4
Displays version information\&.
.RE
.PP
\fB\-p|\-\-portable\fR
.RS 4
Enables portable settings mode using a default configuration file name\&.
.RE
.PP
\fB\-f\fR \fIpath/file\&.conf\fR
.RS 4
This option implies
\fB\-\-portable\fR
as well\&. Reads and writes
\fIpath/file\&.conf\fR
as the portable settings configuration file name\&.
.sp
This configuration file is always a text file with INI format, despite the running Operating System conventions\&.
.RE
.SH "STANDARD OPTIONS"
.PP
The following options apply to all Qt5/6 applications:
.PP
\fB\-style=\fR \fIstyle\fR / \fB\-style\fR \fIstyle\fR
.RS 4
Set the application GUI style\&. Possible values depend on the system configuration\&. If Qt is compiled with additional styles or has additional styles as plugins these will be available to the
\fB\-style\fR
command line option\&.
.RE
.PP
\fB\-stylesheet=\fR \fIstylesheet\fR / \fB\-stylesheet\fR \fIstylesheet\fR
.RS 4
Set the application styleSheet\&. The value must be a path to a file that contains the Style Sheet\&.
.RE
.PP
\fB\-widgetcount\fR
.RS 4
Print debug message at the end about number of widgets left undestroyed and maximum number of widgets existed at the same time\&.
.RE
.PP
\fB\-reverse\fR
.RS 4
Set the application\*(Aqs layout direction to
Qt::RightToLeft\&. This option is intended to aid debugging and should not be used in production\&. The default value is automatically detected from the user\*(Aqs locale (see also
QLocale::textDirection())\&.
.RE
.PP
\fB\-platform\fR \fIplatformName[:options]\fR
.RS 4
Specify the Qt Platform Abstraction (QPA) plugin\&.
.RE
.PP
\fB\-platformpluginpath\fR \fIpath\fR
.RS 4
Specify the path to platform plugins\&.
.RE
.PP
\fB\-platformtheme\fR \fIplatformTheme\fR
.RS 4
Specify the platform theme\&.
.RE
.PP
\fB\-plugin\fR \fIplugin\fR
.RS 4
Specify additional plugins to load\&. The argument may appear multiple times\&.
.RE
.PP
\fB\-qwindowgeometry\fR \fIgeometry\fR
.RS 4
Specify the window geometry for the main window using the X11\-syntax\&. For example: \-qwindowgeometry 100x100+50+50
.RE
.PP
\fB\-qwindowicon\fR \fIicon\fR
.RS 4
Set the default window icon\&.
.RE
.PP
\fB\-qwindowtitle\fR \fItitle\fR
.RS 4
Set the title of the first window\&.
.RE
.PP
\fB\-session\fR \fIsession\fR
.RS 4
Restore the application from an earlier session\&.
.RE
.PP
\fB\-display\fR \fIhostname:screen_number\fR
.RS 4
Switch displays on X11\&. Overrides the
\fBDISPLAY\fR
environment variable\&.
.RE
.PP
\fB\-geometry\fR \fIgeometry\fR
.RS 4
Specify the window geometry for the main window on X11\&. For example: \-geometry 100x100+50+50
.RE
.PP
\fB\-dialogs=\fR \fI[xp|none]\fR
.RS 4
Only available for the Windows platform\&. XP uses native style dialogs and none disables them\&.
.RE
.PP
\fB\-fontengine=\fR \fIfreetype\fR
.RS 4
Use the FreeType font engine\&.
.RE
.SH "SEE ALSO"
.PP
qt5options (7)
.SH "LICENSE"
.PP
This manual page was originally written by
Mehdi Dogguy
<dogguy@pps\&.jussieu\&.fr>
for the Debian GNU/Linux system (but may be used by others)\&.
.PP
Updated for Qt5/6 by
Pedro Lopez\-Cabanillas
<plcl@users\&.sourceforge\&.net>
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 3 or any later version published by the Free Software Foundation; considering as source code all the file that enable the production of this manpage\&.
.SH "AUTHORS"
.PP
\fBMehdi Dogguy\fR <\&dogguy@pps\&.jussieu\&.fr\&>
.RS 4
.RE
.PP
\fBPedro Lopez\-Cabanillas\fR <\&plcl@users\&.sourceforge\&.net\&>
.RS 4
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2009 Mehdi Dogguy
.br
Copyright \(co 2010-2024 Pedro Lopez-Cabanillas
.br
