name: Linux CI

on:
  push:
    branches: [ "devel", "master" ]
  pull_request:
    branches: [ "devel", "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo
  DRUMSTICKNAME: DrumstickV2
  DRUMSTICK_LOCATION: ${{github.workspace}}/DrumstickV2

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: ["x86_64", "aarch64"]
        include:
          - { icon: '🟥', arch: "x86_64", os: "ubuntu-24.04", triplet: "x64-linux-dynamic" }
          - { icon: '🟩', arch: "aarch64", os: "ubuntu-24.04-arm", triplet: "arm64-linux-dynamic" }
    runs-on: ${{ matrix.os }}
    name: '${{ matrix.icon }} Linux ${{ matrix.arch }}'

    steps:
    - uses: actions/checkout@v7

    - name: '${{ matrix.icon }} Download Drumstick artifact'
      uses: dawidd6/action-download-artifact@v24
      with:
        name: ${{env.DRUMSTICKNAME}}-${{matrix.arch}}.tar.gz
        github_token: ${{secrets.GH_PAT}}
        repo: pedrolcl/drumstick
        allow_forks: false
        workflow: linux.yml
        skip_unpack: true

    - name: '${{ matrix.icon }} Extract Drumstick artifact'
      run: |
        if [ -f ${{env.DRUMSTICKNAME}}-${{matrix.arch}}.tar.gz.zip ]; then
          mv ${{env.DRUMSTICKNAME}}-${{matrix.arch}}.tar.gz.zip ${{env.DRUMSTICKNAME}}-${{matrix.arch}}.tar.gz
        fi
        tar xvzf ${{env.DRUMSTICKNAME}}-${{matrix.arch}}.tar.gz

    - name: '${{ matrix.icon }} Install Dependencies'
      run: sudo apt-get install -yq autoconf autoconf-archive automake libtool pkg-config libasound2-dev libpulse-dev libsndfile1-dev

    - name: '${{ matrix.icon }} Set up CMake'
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '4.3.x' # https://github.com/microsoft/vcpkg/issues/53135

    - name: '${{ matrix.icon }} VCPKG Build'
      uses: johnwason/vcpkg-action@v8
      id: vcpkg
      with:
        pkgs: zlib sonivox fluidsynth[sndfile]
        triplet: ${{ matrix.triplet }}
        token: ${{ github.token }}
        revision: master

    - name: '${{ matrix.icon }} Install Qt'
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.11.1'

    - name: '${{ matrix.icon }} Configure CMake'
      id: configuration
      run: >
        cmake ${{ steps.vcpkg.outputs.vcpkg-cmake-config }}
        -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_PREFIX_PATH="${{env.DRUMSTICK_LOCATION}}"
        -DCMAKE_INSTALL_PREFIX=/usr
        -DCMAKE_INSTALL_LIBDIR=lib
        -DCMAKE_INSTALL_RPATH="\$ORIGIN/../lib"
        -DBUILD_DOCS=OFF
        -DINSTALL_DEPENDENCIES=ON

    - name: '${{ matrix.icon }} Build'
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: '${{ matrix.icon }} Install'
      env:
        DESTDIR: ${{github.workspace}}/build/vmpk-v${{steps.configuration.outputs.config_version}}-${{matrix.arch}}.AppDir
      run: cmake --install ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: '${{ matrix.icon }} Archive'
      env:
        INSTALL_LOCATION: vmpk-v${{steps.configuration.outputs.config_version}}-${{matrix.arch}}.AppDir
      run: |
        cd ${{github.workspace}}/build/
        tar -cvzf ${{env.INSTALL_LOCATION}}.tar.gz ${{env.INSTALL_LOCATION}}

    - name: '${{ matrix.icon }} Upload Archive'
      env:
        INSTALL_LOCATION: vmpk-v${{steps.configuration.outputs.config_version}}-${{matrix.arch}}.AppDir
      uses: actions/upload-artifact@v7
      with:
        name: ${{env.INSTALL_LOCATION}}
        path: ${{github.workspace}}/build/${{env.INSTALL_LOCATION}}.tar.gz
        retention-days: 90
        overwrite: true
        archive: false

    - name: '${{ matrix.icon }} Upload AppImage'
      env:
        INSTALL_LOCATION: vmpk-v${{steps.configuration.outputs.config_version}}-${{matrix.arch}}.AppImage
      uses: actions/upload-artifact@v7
      with:
        name: ${{env.INSTALL_LOCATION}}
        path: ${{github.workspace}}/build/${{env.INSTALL_LOCATION}}
        retention-days: 90
        overwrite: true
        archive: false
